mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls',namespace = 'polls')),
    path('registration/', include('registration.urls', namespace = 'registration')),

]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'

urlpatterns = [
    # path('newuser/', views.signup,name='signup'),
    path('choiceform/',views.choice_form,name='choice_view'),
    path('questionform/<int:id>',views.edit_question_form,name='question_view'),
    path('newquestion/',views.create_new_question,name='new_question_view'),
    path('',views.pollhome, name = 'home'),
    path('<slug>/result/',views.results, name = 'result'),
    path('<slug>/',views.detail, name = 'detail'),
    path('<slug>/vote/', views.vote, name='pollvote'),
    
    
]

registration/urls.py
from django.urls import path
from . import views
app_name = 'registration'

urlpatterns = [
    path('register/', views.signup, name='signup'),
    path('signin/', views.sign_in, name = 'sign_in'),
]

polls/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_description = models.CharField(max_length = 1000, blank=True)
    pub_date = models.DateTimeField('date published')
    slug = models.SlugField(max_length=255, unique=False, null = True)

    class Meta:
        verbose_name_plural = 'Questions'
        ordering = ['-pub_date']

    def __str__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.question_text)
        super(Question, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return '/{}/{}/'.format('polls',self.slug)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return 'Choice for : {}'.format(self.question.question_text)

polls/forms.py
from django import forms
from .models import Question
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ChoiceForm(forms.Form):
    question = forms.CharField(max_length = 100) #"Type in any question you want")
    choice_text = forms.CharField(max_length=100) #, default = "Provide some description here")
    

class QuestionForm(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = "__all__"
        #exclude = ['slug']

class CreateQuestionForm(forms.ModelForm):
    
    class Meta:
        model = Question
        exclude = ['slug']

# class UserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ('username','password','first_name','last_name')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404,render,redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,logout
from .models import Question, Choice


from .forms import ChoiceForm, QuestionForm, CreateQuestionForm #,UserForm


def pollhome(request):
    questions_list = Question.objects.all()[0:4]
    template = 'polls/home.html'
    context = {'questions':questions_list}


    return render(request,template,context)
    #return HttpResponse(output)

def results(request,slug):
    question = get_object_or_404(Question, slug=slug)
    return render(request, 'polls/results.html', {'question': question})


def detail(request, slug):
    """
    Returns a path to the detail view for a single question
    """
    try:
        question = Question.objects.get(slug=slug)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})


def vote(request, slug):
    question = get_object_or_404(Question, slug=slug)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:result', args=(question.slug,)))



def choice_form(request):
    
    form = ChoiceForm()
    template = 'polls/choiceview.html'
    context = {
        'form':form
    }
    return render(request,template,context = context)

def edit_question_form(request,id):

    question = Question.objects.get(pk=id)
    form = QuestionForm(instance = question)
    template = 'polls/choiceview.html'
    context = {
        "form":form,

    }
    return render(request,template,context = context)

def create_new_question(request):    
    
    if request.method == 'POST':
        q_text = request.POST.cleaned_data['question_text']
        new_question = Question(question_text = q_text)
        form = CreateQuestionForm(request.POST,instance=new_question) 
        if form.is_valid():
            form.save()
            HttpResponseRedirect('/polls/home.html')
    
    else:
        form = CreateQuestionForm()
    

    template = 'polls/newquestion.html'
    context = {
        "form":form
    }

    return render(request = request, template_name=template, context = context)


def signup(request):
    #template = 'registration/signup.html'
    #context = {'form':form}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('polls:home')
    else:
        form = UserCreationForm()
    
    return render(request,'polls/newuser.html',{'form':form})

templates/base.html
<!DOCTYPE html>

<html lang="en">
{% include "head.html" %}

<body>

{% comment %} {% include "head.html" %} {% endcomment %}

    {% block header %}
        {% include "header.html" %} 
     {% endblock %} 

    <!-- Hero  -->
    {% block hero %}
        {% include "hero.html" %}
    {% endblock %}

    <!--Counts-->
    {% block counts %}
        {% include "counts.html" %}
    {% endblock %}

    <!-- Footer -->
    {% block footer%}
        {% include "footer.html" %}
    {% endblock %}
    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    
    <!--JS-->
    {% include "scripts.html" %}
</body>
</html>

templates/counts.html
{% load static %}

<section id="counts" class="counts section-bg">
    <div class="container">

      <div class="row justify-content-end">

        <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
          <div class="count-box">
            <span data-purecounter-start="0" data-purecounter-end="65" data-purecounter-duration="2" class="purecounter"></span>
            <p>Happy Clients</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
          <div class="count-box">
            <span data-purecounter-start="0" data-purecounter-end="85" data-purecounter-duration="2" class="purecounter"></span>
            <p>Projects</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
          <div class="count-box">
            <span data-purecounter-start="0" data-purecounter-end="30" data-purecounter-duration="2" class="purecounter"></span>
            <p>Years of experience</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
          <div class="count-box">
            <span data-purecounter-start="0" data-purecounter-end="20" data-purecounter-duration="2" class="purecounter"></span>
            <p>Awards</p>
          </div>
        </div>

      </div>

    </div>
  </section>

templates/footer.html
{% load static %}

<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>AmaliTech Ghana
          </h6>
          <p>
          AmaliTech is a social IT company specialised in trainig young graduates in IT skils...
          
          
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
           Specialization
          </h6>
          <p>
            <a href="#!" class="text-reset">Software Development & Evolution</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Data Science and Analytics</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Sales Force</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Media and Design</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Home</a>
          </p>
          <p>
            <a href="#!" class="text-reset">About</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Contact</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i>SSNIT Rd </p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@amalitech.org
          </p>
          <p><i class="fas fa-phone me-3"></i> +233 546 783 426</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
    <title>OnePage Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
  
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
  
    <!-- =======================================================
    * Template Name: OnePage - v4.2.0
    * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
  </head>

templates/header.html
{% load static %}

<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'polls:home' %}">GhanaPolls</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'polls:home' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          
          <li><a class="nav-link scrollto" href="{% url 'registration:signup' %}">Signup</a></li>
          <li><a class="getstarted scrollto" href="#about">Cast a Vote</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>

templates/hero.html
{% load static %}
<section id="hero" class="d-flex align-items-center">
  <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
    <div class="row justify-content-center">
      <div class="col-xl-7 col-lg-9 text-center">
        <h1>Ghana Polls</h1>
        <h2>Interesting and Fun Polls in Ghana</h2>
      </div>
    </div>
    <div class="text-center">
      <a href="{% url 'polls:home' %}" class="btn-get-started scrollto">Cast A Vote</a>
    </div>
    
    <div class="row icon-boxes">
      {% for question in questions %}
      <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
        <div class="icon-box mb-3">
          <div class="icon"><i class="ri-stack-line"></i></div>
          <h4 class="title"><a href="{% url 'polls:detail' question.slug %}">{{ question.question_text }}</a></h4>
          <p class="description">{{question.question_description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    
  </div>

</section>

<div class="container">
  
     <nav aria-label="...">
     <ul class="pagination pagination-lg"  style="margin-left: 400px">
       <li class="page-item active" aria-current="page">
         <span class="page-link">1</span>
       </li>
       <li class="page-item"><a class="page-link" href="#">2</a></li>
       <li class="page-item"><a class="page-link" href="#">3</a></li>
       <li class="page-item"><a class="page-link" href="#">4</a></li>
       <li class="page-item"><a class="page-link" href="#">5</a></li>
     </ul>
    </nav>
</div>

templates/navigations.html
{% load static %}

    <header id="header" class="fixed-top">
   <div class="container d-flex align-items-center justify-content-between">
     <h1 class="logo"><a href="index.html">GhanaPolls</a></h1>
     <nav id="navbar" class="navbar">
       <ul>
         <li><a class="nav-link scrollto active" href="{% url 'polls:home' %}">Home</a></li>
         <li><a class="nav-link scrollto" href="#about">About</a></li>
         <li><a class="nav-link scrollto" href="#services">Contact</a></li>
     </nav>
   </div>
 </header>

templates/polls/choiceview.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block header %}
<h1>We are happy to be on the coice view page</h1>
{% endblock %}

{% block content %}
    <form action="#" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="button" value='Submit'>
    </form>

{% endblock %}

{% block footer %}{% endblock %}

templates/polls/detail.html
<!DOCTYPE html>
{% extends "base.html" %}


{% block hero %}
<section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>{{ question.question_text }} </h1>
          <p>Published on: <span>{{ question.pub_date }}</span></p>
        </div>
      </div>
      <!-- Choices Here -->

      
      <div class = 'container text-center'>
        <form action="{% url 'polls:pollvote' question.slug %}" method="post">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                
                
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text|title }}</label><br>
        
            
            {% endfor %}
            <div class="text-center">
                <input class="btn btn-lg btn-success mt-4" type="submit" value="Vote">
            </div>
        </form>
      </div>

      <!-- <div class="text-center">
        <a href="{% url 'polls:home' %}" class="btn-get-started scrollto">Vote</a>
      </div>
       -->
      <div class="row icon-boxes">
        {% for question in questions %}
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box">
            <div class="icon"><i class="ri-stack-line"></i></div>
            <h4 class="title"><a href="{% url 'polls:detail' question.slug %}">{{ question.question_text }}</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>
        {% endfor %}
      </div>
      
    </div>
  </section>
{% endblock %}

templates/polls/home.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block header %}
{% include 'header.html' %}
{% endblock%}

{% block navigations %}{% endblock %}
<!-- Loop through questions and create a list of exisiting questions -->
{% block content %}

{% for q in questions %}
<ul>
        
      <li><a href = "{% url 'polls:detail' q.slug %}">{{ q.question_text }}</a></li>
      
</ul>

{% endfor %}

{% endblock %}

templates/polls/newquestion.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block header %}
<h1>New Question</h1>
{% endblock %}

{% block content %}
    <form action="{% url 'polls:new_question_view' %}" method="post">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="button" value='Submit'>
    </form>

{% endblock %}

{% block footer %}{% endblock %}

templates/polls/newuser.html
<div class='container mt-5'>

</div>
<div class='container mt-5'>
    <h2>Signup Form</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">
    </form>
</div>

    

templates/polls/results.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block header %}

{% endblock %}


{% block hero %}
    <div class="container mt-5">
    <h1>Results for: {{ question.question_text }}</h1>
    {% for choice in question.choice_set.all %}
        <ol class="list-group m-2">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                  <div class="fw-bold">{{ choice.choice_text }}</div>
                </div>
                <span class="badge bg-danger rounded-pill">{{ choice.votes }}</span>
            </li>
        </ol>
    {% endfor %}
     <a href="{% url 'polls:pollvote' question.slug %}" class="btn btn-lg btn-primary w-100">Vote again?</a>
    </div>

{% endblock %}








{% block content %}

 {% endblock %}

{% block footer %} {% endblock %}

templates/scripts.html
{% load static %}
<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>